---
- name: Setup pre-commit hook in repo
  copy:
    src: pre-commit
    dest: "{{ ansible_linters_repo_path }}/git/hooks/"
  notify: h_make_pre-commit_hook_executable

- name: Setup linters in repo root 
  template:
    src: pre-commit-config.yaml.j2
    dest: "{{ ansible_linters_repo_path }}/.pre-commit-config.yaml"
...
